name: Deploy to Production

on:
  push:
    branches:
      - main

jobs:
  lint-frontend:
    name: Lint Frontend
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run frontend linting
        run: npm run lint:frontend

      - name: Check frontend formatting
        run: npm run format:check
        working-directory: ./frontend

  lint-infrastructure:
    name: Lint Infrastructure
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run infrastructure linting
        run: npm run lint:infrastructure

      - name: Check infrastructure formatting
        run: npm run format:check
        working-directory: ./infrastructure

  test-frontend:
    name: Test Frontend
    runs-on: ubuntu-latest
    needs: lint-frontend

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run frontend tests
        run: npm run test:frontend

  test-infrastructure:
    name: Test Infrastructure
    runs-on: ubuntu-latest
    needs: lint-infrastructure

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run infrastructure tests
        run: npm run test:infrastructure

  build-frontend:
    name: Build Frontend
    runs-on: ubuntu-latest
    needs: test-frontend

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build frontend
        working-directory: ./frontend
        env:
          NEXT_PUBLIC_COGNITO_USER_POOL_ID: ${{ secrets.PROD_NEXT_PUBLIC_COGNITO_USER_POOL_ID }}
          NEXT_PUBLIC_COGNITO_CLIENT_ID: ${{ secrets.PROD_NEXT_PUBLIC_COGNITO_CLIENT_ID }}
          NEXT_PUBLIC_COGNITO_DOMAIN: ${{ secrets.PROD_NEXT_PUBLIC_COGNITO_DOMAIN }}
          NEXT_PUBLIC_COGNITO_REGION: ${{ secrets.PROD_NEXT_PUBLIC_COGNITO_REGION }}
          NEXT_PUBLIC_API_GATEWAY_URL: ${{ secrets.PROD_NEXT_PUBLIC_API_GATEWAY_URL }}
        run: npm run build

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: frontend-build
          path: frontend/out/
          retention-days: 1

  deploy:
    name: Deploy to AWS
    runs-on: ubuntu-latest
    needs: [build-frontend, test-infrastructure]
    environment: production

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: frontend-build
          path: frontend/out/

      - name: Build infrastructure
        working-directory: ./infrastructure
        run: npm run build

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Deploy to AWS
        working-directory: ./infrastructure
        run: npx cdk deploy -c env=prod --require-approval never
